services:
  postgres:
    image: postgres:latest
    platform: linux/arm64/v8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-forlogic-api
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: